name: Deploy to Production

on:
  workflow_run:
    workflows: ["CI for Laravel Package"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Production Server
        run: echo "Deployment simulation completed successfully!"
        # env:
        #   SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        #   SERVER_USER: ${{ secrets.SERVER_USER }}
        #   SERVER_IP: ${{ secrets.SERVER_IP }}
        # run: |
        #   echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
        #   ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << 'EOF'
        #     cd /var/www/node379
        #     composer update --no-interaction --prefer-dist
        #   EOF
